importScript("data/scripts/DeltaCharacter");
var character = createCharacter("Kris", "kris", "characters/kris", [
	{
		name: "idle",
		prefix: "idle",
		fps: 12,
		loop: true,
		endFrame: 5,
	},
	{
		name: "dead",
		prefix: "dead",
		fps: 1,
		loop: true,
	},
	{
		name: "attackprep",
		prefix: "attackprep",
		fps: 1,
		loop: true,
		offset: [0, 5],
	},
	{
		name: "actprep",
		prefix: "actprep",
		fps: 4,
		loop: true,
	},
	{
		name: "itemprep",
		prefix: "itemprep",
		fps: 4,
		loop: true,
	},
	{
		name: "attack",
		prefix: "attack",
		fps: 12,
		loop: false,
		offset: [0, 5],
	},
	{
		name: "defend",
		prefix: "defend",
		fps: 12,
		loop: false,
	},
	{
		name: "hurt",
		prefix: "hurt",
		fps: 1,
		loop: false,
	},
	{
		name: "swordjump",
		prefix: "swordjump",
		fps: 12,
		loop: true,
	},
	{
		name: "battlestart",
		prefix: "battlestart",
		fps: 12,
		loop: false,
	},
	{
		name: "victory",
		prefix: "victory",
		fps: 12,
		loop: false,
	},
	{
		name: "idle0",
		prefix: "idle_overworld_up",
		fps: 12,
		loop: true,
		endFrame: 0,
	},
	{
		name: "idle1",
		prefix: "idle_overworld_right",
		fps: 12,
		loop: true,
		endFrame: 0,
	},
	{
		name: "idle2",
		prefix: "idle_overworld_down",
		fps: 12,
		loop: true,
		endFrame: 0,
	},
	{
		name: "idle3",
		prefix: "idle_overworld_left",
		fps: 12,
		loop: true,
		endFrame: 0,
	},
	{
		name: "walk0",
		prefix: "idle_overworld_up",
		fps: 12,
		loop: true,
		endFrame: 3,
	},
	{
		name: "walk1",
		prefix: "walk_overworld_right",
		fps: 12,
		loop: true,
		endFrame: 3,
	},
	{
		name: "walk2",
		prefix: "walk_overworld_down",
		fps: 12,
		loop: true,
		endFrame: 3,
	},
	{
		name: "walk3",
		prefix: "walk_overworld_left",
		fps: 12,
		loop: true,
		endFrame: 3,
	},
], 4, 90, 0xFF00AAFF, false, []);
characters.push(character);